#ifdef __OPTION_TESTS
#include "../test/option.h"
#include "../test/munit.h"
#endif

#ifndef __OPTION_TESTS
#include "option/option_u8.h"
#endif
#include "option_template.h"

OPTION_TYPE_FACTORY(u8);
OPTION_TYPE_FUNCTION_FACTORY(u8);
OPTION_TYPE_MAP_FUNCTION_FACTORY(u8, i8);
OPTION_TYPE_MAP_FUNCTION_FACTORY(u8, i16);
OPTION_TYPE_MAP_FUNCTION_FACTORY(u8, i64);
OPTION_TYPE_MAP_FUNCTION_FACTORY(u8, u8);
OPTION_TYPE_MAP_FUNCTION_FACTORY(u8, u16);
OPTION_TYPE_MAP_FUNCTION_FACTORY(u8, u32);
OPTION_TYPE_MAP_FUNCTION_FACTORY(u8, u64);
OPTION_TYPE_MAP_FUNCTION_FACTORY(u8, float);
OPTION_TYPE_MAP_FUNCTION_FACTORY(u8, double);
OPTION_TYPE_MAP_FUNCTION_FACTORY(u8, size);

