#ifdef __OPTION_TESTS
#include "../test/option.h"
#include "../test/munit.h"
#endif

#ifndef __OPTION_TESTS
#include "option/option_i64.h"
#endif
#include "option_template.h"

OPTION_TYPE_FACTORY(i64);
OPTION_TYPE_FUNCTION_FACTORY(i64);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i64, i8);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i64, i16);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i64, i64);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i64, u8);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i64, u16);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i64, u32);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i64, u64);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i64, float);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i64, double);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i64, size);

