#ifdef __OPTION_TESTS
#include "../test/option.h"
#include "../test/munit.h"
#endif

#ifndef __OPTION_TESTS
#include "option/option_i16.h"
#endif
#include "option_template.h"

OPTION_TYPE_FACTORY(i16);
OPTION_TYPE_FUNCTION_FACTORY(i16);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i16, i8);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i16, i16);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i16, i64);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i16, u8);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i16, u16);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i16, u32);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i16, u64);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i16, float);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i16, double);
OPTION_TYPE_MAP_FUNCTION_FACTORY(i16, size);

